name: Update README with recent GitHub activity

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: readme-actions/recent-activity@v2.3.1
        with:
          GH_USERNAME: surafelbkassa
